### ISSUE TITLE
instead of port number, should give process/program which is responsible. 

### ISSUE THREAD

**Issue by shirishag75** [raboof/nethogs#105]
See the following -

![pid-process-portnumber](https://cloud.githubusercontent.com/assets/727626/20459625/c813bec6-aeee-11e6-872f-16c1ccb784d8.png)

In the picture above the first one neither displays a pid or a program for which it is getting traffic. And then qbittorrent is the one below it. My best guess is that the first one is part of qbittorrent only but it is a 'guess' (from port number and such details). If there was at least a PID number there could be some attempt to trace where the traffic is originating/going to. Not having such information also has security implications.

**Comment by raboof** [comment]
Unfortunately this is essentially impossible.

The way nethogs works is that it monitors network traffic on your machine. For each packet, it finds the connection that packet belongs to. A connection is not directly associated with a PID, but has an inode number. That inode number is associated with a process.

The problem is that for example bittorrent can use connections that are really short-lived. Because of that, it can happen that we found a packet during monitoring, but when we go look for the connection/inode or PID, it has already disappeared.

We could cheat a little and match those packets to processes listening on the port, but that would be a 'guess' which you mention you'd like to avoid.

If not having each connection matched to a process has security implications for you, I'm curious about your use case.
