### ISSUE TITLE
crash after openning and quickly closing chromium

### ISSUE THREAD

**Issue by AquariusPower** [raboof/nethogs#164]
I am using: NetHogs version 0.8.5-45-g2e8a4f8 (cloned a few days ago here)
I run it like `nethogs -d 1 -c 0 -v 3 -a`

crashes if for ex. I open chromium and instantly closes it. 

When I turn on airplane mode and off again, it may crash too.

I will try to get a stacktrace.

**Comment by raboof** [comment]
A stacktrace would be great!

What distro/device are you on that you have an 'airplane mode'?

**Comment by AquariusPower** [comment]
xD
I am using ubuntu 16.04
I connect thru my smartphone usb thetering :)
whenever I think it is spending too much of my 100MB limit w/o a good reason (like something I opted for) I just turn on airplane mode on the smartphone and smile :)

**Comment by AquariusPower** [comment]
I am still trying to get that stack.
I am running it like: `sudo -k nemiver rxvt -e nethogs -d 1 -c 0 -v 3 -a`. Any better gdb command suggestion? I am using nemiver because is easy to see the context stack trace on error but most importantly, it accepts I pass a lot of parameters for the target application in the command line! while I couldnt do that in `ddd`.

So, After 3 days (yes restart computer 3 times), a sudden close happened, but it was without any errors! I dont understand?

I tried to  run it with `-b` option, but the output is not the nice list so I had to drop it.
I wonder if it could show the nice list but log the bug hunt data to some file in a non temporary location? it could be `-B <strFullPathLogFile>` (a new parameter for compatibility).

**Comment by gunnar12** [comment]
crash/

Just running nethogs inside the gdb debugger gives some info, althgh nethogs not made with debugging symbols and all the debug stuff.
Guess you have to compile your own ./nethogs for it?? (just asked for a debug-makefile)

with gdb installed something like this

sudo gdb s--args ./nethogs your0own-arguments

and then "run" at gdb prompt.

(long time since I last struggled with gdb)

Gunnar

Note, my crashes come only with the new -l argument that lists cmdline of process too, not just PID and name.

**Comment by gunnar12** [comment]
if you compile your own nethogs gdb will find the source files (which it doesnt when you run an installed binary executable, except by telling gdb where it is or similar)

Although you wont get "all" debug info, you will (probably) get the name of the subroutin-module where it crashed, plus some garble stuff which gdb wld use to to find the exact line of code where nethogs crashed  (thats the debug info that one gets when compiling for debug)

This very basic info is embedded in the compiled-linked program, but can also be totally stripped of it.

Note, "really" debug compiled code additionally doesnt optimize neither the source nor assembly code so that one additionally can see every variable and step the code forwards, sometimes even backwards,.
(different levels of debug compilation)

Unluckily this highest level of "line-by-line" debug info also changes how the code is executed, some bad code cant found.
IE,often the debug code doesnt crash while the release-optimized-code still crashed.
Thats when one has to step down to understanding the  machine-assembly code the compiler produces from the C or whatever hihger level code one uses.

Gunnar

**Comment by raboof** [comment]
possibly fixed by #175, please reopen if it occurs after that
