### ISSUE TITLE
Find out process running on Linux OS which consumed network bandwidth historically

### ISSUE THREAD

**Issue by kaushalshriyan** [raboof/nethogs#208]
I am running CentOS Linux release 7.9.2009 (Core). Is there a way to find out which process consumed network bandwidth during a specific time period using nethogs? For example, the Nginx process consumed how much network traffic on Sept 01, 2021.

**Comment by raboof** [comment]
No.

Nethogs is mainly intended for 'live' use: viewing the bandwidth usage 'right now'.

It is possible to capture the data from a nethogs process (for example with `nethogs -v 2 -t` and post-process this data, but it's not really what nethogs was intended for and might not yield accurate results.

Since you're using 'Nginx' as an example, it sounds like you want to monitor the traffic of a server. On a server, perhaps you don't really need the process information: you already know that traffic using the local port 80 or 443 will be Nginx traffic. In that case it would probably be better to use traffic monitoring tools that work on the port numbers directly, rather than (like Nethogs) also try to do the translation from connection to process 'on the fly'.

Does that help?
