### ISSUE TITLE
on each launch nethogs show different top usage IP

### ISSUE THREAD

**Issue by xgdgsc** [raboof/nethogs#241]
![image](https://user-images.githubusercontent.com/1189869/185294726-adc553eb-c6d1-4e92-8fa5-11b3363ed6fa.png)

on each launch nethogs show different top usage IP with similar bandwidth usage , I was trying to use [gotty](https://github.com/sorenisanerd/gotty/) to serve nethogs results for users to checkout who is responsible for usage. But I noticed each launch shows a different top IP address, rendering the results useless. So I switched to iftop, which shows same top results no matter when I launch it.

**Comment by NeilZhy** [comment]
ask a different question： what does the result {ip}:{port} mean?

**Comment by raboof** [comment]
I don't have time to dig into the source code right now, but from memory:
* nethogs is designed to group traffic by local process.
* when it sees traffic, it checks whether the 'local' ip:port already has a process associated with it. If so, it adds the traffic to that process. If not, it creates a new 'process' to count that traffic
* when no process is found, it shows the local and remote ip:port for the first connection it saw

I suspect that explains the behavior you're describing: the process at local ip:port `192.168.101.199:2049` is what's causing the majority of your traffic, and the 'remote' ip:port is simply an 'example' of a connection to that process.

If you want to break down your network traffic by remote user instead of by local process, indeed a tool like iftop is likely more useful in your case.

**Comment by xgdgsc** [comment]
Thanks. I understand the difference now.
