### ISSUE TITLE
What is "unknown UDP" ?

### ISSUE THREAD

**Issue by sang-shelton** [raboof/nethogs#281]
![Screenshot_20241018_115155](https://github.com/user-attachments/assets/f24b5a63-c055-41a5-93f7-792843efe2f7)

i am running nethogs as root and as you can see in the picture above, i am getting "unknown UDP" highlighted with the red box.

What is this "unknown UDP" ?
How can i know what traffic this is ?

**Comment by sang-shelton** [comment]
> This is UDP traffic that could not be related to any processes in `/proc/net/udp` or `/proc/net/udp6`.
> 
> To diagnose further you might want to look at the packets with other tools like wireshark.

Thanks for help.

i don't know much about this, but isn't it weird that some traffic is not related to any process ?! or maybe that if belongs to a process but nethogs could not identify it ?

**Comment by raboof** [comment]
This is indeed weird!

For incoming traffic, it is possible this is traffic that isn't related to a process, but just sent to you incorrectly. This is somewhat unlikely though - it's probably indeed the case that nethogs could not identify the process.

Unfortunately, at the time of writing, the Linux Kernel did not provide a reliable way to associate traffic with processes, which is why nethogs just does a 'best effort' search. Possibly nowadays using eBPF we could more reliable - but that would also make it require more privileges. For now the current implementation seems to be the right trade-off.

**Comment by ErezBinyamin** [comment]
I am writing an eBPf addition to nethogs on a local fork. Is there any interest in me eventually pushing upstream?

So far performance has been fine, but additional dependencies and permissions are needed

**Comment by raboof** [comment]
That sounds really cool! As long as it's still possible to have the 'non-eBPF' and 'eBPF' implementations side-by-side somehow I think that would be great to have!
