### ISSUE TITLE
Resets  counters

### ISSUE THREAD

**Issue by vinogradovs** [raboof/nethogs#29]
Nethogs resetted "received" counter 2 times during 30 minutes run.
Counters numbers were about 3-4Gb in Megabytes view  before resets.

**Comment by raboof** [comment]
Interesting, might be an overflow - we count bytes - let's see if we can widen that type :)

**Comment by jantman** [comment]
I'm pretty sure this is an overflow since we're using ``uint32_t`` to count bytes, and maximum for that type (2^32 - 1) works out to be approximately 4.2GB (and regardless of what view you specify, the totals are stored as bytes and converted to the unit you asked for). That's stored per connection, but it's also summed per process... so I think it's quite likely that (especially on a busy server or a desktop with a process that's doing a lot of network IO like a game, torrent client, single-process browser, or streaming video) it can wrap around - that will happen with any process that sends or receives more than 4.2 GB.

If we bumped all of the total bytes counters from uint32_t to uint64_t, we'd end up consuming a bit more memory (an additional 64 bytes per connection, plus some program-wide overhead for summing) and change the public API of libnethogs, but we'd be able to count 2^64 - 1 bytes, or __18.4 exabytes__ (that's 18,446,744.1 terabytes) before wrapping around.

**Comment by raboof** [comment]
Sounds like a good idea to me!

**Comment by jantman** [comment]
Ok, I'll give a try at a PR for this one later today.

**Comment by raboof** [comment]
Thanks for this fix @jantman
