### ISSUE TITLE
Electron-based GUI version of nethogs

### ISSUE THREAD

**Issue by iamtekeste** [raboof/nethogs#4]
@raboof I am planning to build a tool similar to  nethogs but it will GUI tool instead of command line. Can you point me in the right direction? 

Like 
can I build this on top of nethogs?
if not how are you collecting the bandwidth info for the process?

Thank you in advance.

**Comment by raboof** [comment]
That would be great!

There are a couple of ways to approach this. From the top of my head:
* build it from the same sources, e.g. adding a 'gui.cpp' next to the existing 'cui.cpp' and building 2 executables instead of just the CLI version
* turn the nethogs code into a shared object and load that into the GUI
* start nethogs from the GUI app, consume its output and present it in the GUI

I think the first and third options are probably most suitable. The first option would require you to fork nethogs and it's kind of unclear whether a gui could/should be merged back. The last option would probably also require changes to nethogs, but I'm definitely open to merging them faster.

**Comment by sharedmit** [comment]
I was planning to implement it using http://electron.atom.io/, since I am already familiar with web technologies such as nodejs. I think the last one seems easier to achieve. I will share with you a simple mock up of the GUI. I am thinking It would look good and easily accessible it was a menu bar app.

**Comment by raboof** [comment]
Cool. As Electron is based heavily on 'web' technologies, I'd say it'd make sense to either expose the data collected by nethogs through some 'web-style' api, or go all-the-way and re-implement it in java/coffee/typescript. 

I think I'd lean towards the former. I know there's been a lot of movement in storing, exchanging and visualizing time-series data recently, though I haven't been paying close attention. Have you noticed any good (standard?) API's emerging that would be a good fit for nethogs' data?

**Comment by sharedmit** [comment]
I am not aware of such kind of standard. But I was thinking to run your cpp file. Node has a way to run cpp files. Can you point me to the cpp file you are using to collect the bandwidth usage info?

And also do u think we could run nethogs without sudo?

**Comment by raboof** [comment]
Basically all nethogs does is collecting the bandwidth usage info ;). Not sure if there's any specific parts that I could highlight.

Running nethogs without sudo might be possible if you can give your user the CAP_NET_RAW capability (http://linux.die.net/man/7/capabilities), but I'm not sure if I've ever tried that.

**Comment by sharedmit** [comment]
Is there a command that you run to get the bandwidth usage info? Like `ps aux` ?

Btw thank you so much for this conversation.

**Comment by raboof** [comment]
No, I monitor the traffic with `libpcap` and then determine which packets belong to which application.

**Comment by sharedmit** [comment]
Ok thank you. I will let you know if I made any progress.

**Comment by chozabu** [comment]
something like this https://github.com/akshayKMR/hogwatch ?
Linking - since this thread is one of the first results for nethogs gui - and is perhaps not going anywhere

**Comment by raboof** [comment]
Thanks for linking - indeed I think we can close this issue for now. I already added a link to hogwatch to the README.
